# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

variables:
- group: ado-agent-cloud-init-lib

pool: customagentspool

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
    which az
    which kubectl
    which terraform
  displayName: 'Run a multi-line script'

- task: Kubernetes@1
  displayName: kubectl apply using arguments
  inputs:
    connectionType: Azure Resource Manager
    azureSubscriptionEndpoint: ARM_SUBSCRIPTION
    azureResourceGroup: $(AKS-RG)
    kubernetesCluster: $(AKS-CLUSTER)
    command: apply
    arguments: -f aks-helloworld-one.yaml
